name: xcube-sh
channels:
  - conda-forge
  - defaults
dependencies:

  # Required
  - xcube >=0.3.0.dev0
  - oauthlib >=3.0
  - pip >=19.1

  # Inspection
  - jupyterlab
  - matplotlib

  - pip:
    # Required
    - requests_oauthlib
