name: xcube-sh

channels:
  - conda-forge

dependencies:
  - click
  - numcodecs
  - numpy
  - oauthlib >=3.0
  - pandas
  - psutil
  - pyproj
  - requests
  - requests-oauthlib >=1.3
  - xarray
  - xcube >=0.10
  - zarr
